# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of Approver'
        required: true
        type: string
      deployment_key:
        description: 'Approval Key'
        required: true
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    
    environment: Test

    env:
        ENV_DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
        
    steps:
    - name: checking for approval
      if: ${{ env.ENV_DEPLOYMENT_KEY != inputs.deployment_key }}
      run: echo "Deployment approval failed for user ${{ inputs.name }}!" && exit 1
    - name: log approval success
      run: echo "User ${{ inputs.name }} successfully approved the deployment!"
