# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of Approver'
        required: true
        type: string
      deployment_key:
        description: 'Deployement Key'
        required: true
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: list keys
      env:
        DEPLOYMENT_KEY: ${{ secrets.deployment_key }}
      run: echo "ENV key = $env:DEPLOYMENT_KEY" && echo "INPUT key = ${{ inputs.deployment_key }}"
    - name: check for approval
      env:
        ENV_DEPLOYMENT_KEY: ${{ secrets.deployment_key }}
      if: ${{ env.ENV_DEPLOYMENT_KEY != inputs.deployment_key }}
      run: echo "Approval failed!" | exit 1
