# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of Approver'
        required: true
        type: string
      deployment_key:
        description: 'Deployement Key'
        required: true
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
    - name: list keys
      run: echo env key = env.deployment_key | echo input key = inputs.deployment_key
    - name: check for approval
      if: ${{ env.deployment_key != inputs.deployment_key }}
      run: echo "Approval failed!" | exit 1
